### ISSUE TITLE
About dataset split

### ISSUE THREAD

**Issue by YeeZ93** [360-SSOD/download#1]
您好，
您好，

十分感谢您的工作： Stage-wise Salient Object Detection in 360°Omnidirectional Image via Object-level Semantical Saliency Ranking

我对您的工作很感兴趣并且可能需要用到您的数据集做之后的研究。

我下载到您的数据集，里面有755个带_TR后缀的和350个带_TE后缀的。但是您的文章中说用到850个作为training，其余为testing。请问实际的split是多少呢？

十分感谢！

**Comment by 360-SSOD** [comment]
您好！感谢您关注我们的工作！

很抱歉我的失误导致您的困惑，训练集为850，测试集255。

导致这一失误的原因是前段时间因一些特殊不可抗力原因，国内无法访问谷歌网盘不便于维护，我们将数据集迁移到百度网盘，迁移过程中我们错误的将之前做数据集评估时候的一个TR755TE350数据集发布到百度网盘，现在已经更新数据集，数据集地址为：链接: https://pan.baidu.com/s/1MGTA0uezlfk6LW9H1UI2PA 提取码: 8j8d 

再次感谢您的提醒！

祝：好！

**Comment by 360-SSOD** [comment]
另：Github登录不稳定，我的邮箱是mgx@jbeta.net，如后续有问题可直接邮件联系我~
再次感谢关注我们的工作！

**Comment by YeeZ93** [comment]
好的 非常感谢！
