### ISSUE TITLE
train model

### ISSUE THREAD

**Issue by zsevenj** [360-SSOD/download#2]
Thank you for sharing the code. Could you also share trained models?

**Comment by LCA-0907** [comment]
Same question.
Would you share the trained models and the dataset?
I checked the link to baidu cloud but didn't found them.

**Comment by 360-SSOD** [comment]
@zsevenj @LCA-0907 
I'm very sorry, I haven't checked the Issue recently.
I have updated the link.

Model:  https://pan.baidu.com/s/1GcSzPuEAxNywF18zMX_gZg password: j9gx 
Results: https://pan.baidu.com/s/1bgkIEnkNVwQpjiBqLv81bQ password:  bjk4
Dataset: https://pan.baidu.com/s/1xPx2OVfvRXp2ZJwjA3MtLw password:  p3b2 

Thanks for following our work ！

**Comment by LCA-0907** [comment]
@360-SSOD 
Thank you for the reply and updated files!
I download the model and the dataset successfully, however I noticed that this code takes .pth as the pretrained weights while the files in the model.zip are caffemodels.
I've tried to convert the caffemodels into pth but faced some problems.
Would you share the pth models or the tools to convert between these two types of files? Thank you very much.

**Comment by winterswee** [comment]
> @zsevenj @LCA-0907 I'm very sorry, I haven't checked the Issue recently. I have updated the link.
> 
> Model: https://pan.baidu.com/s/1GcSzPuEAxNywF18zMX_gZg password: j9gx Results: https://pan.baidu.com/s/1bgkIEnkNVwQpjiBqLv81bQ password: bjk4 Dataset: https://pan.baidu.com/s/1xPx2OVfvRXp2ZJwjA3MtLw password: p3b2
> 
> Thanks for following our work ！

Hi， I tried the links but they are out of date. Can you share the latest available links? Besides, can you add the detailed 
 training steps in the readme file?

**Comment by winterswee** [comment]
Would you share the trained models?
I checked the link to Baidu cloud but didn't find them.
