### ISSUE TITLE
百度云链接已经失效了

### ISSUE THREAD

**Issue by cenchaojun** [360-SSOD/download#3]
可以再次提供新的链接吗？或者google云的，谢谢

**Comment by 360-SSOD** [comment]
您好，新的链接如下，如再失效，请留言联系我哈~

链接: https://pan.baidu.com/s/1ivAKHceZrh5uHRiKLiHcTw?pwd=c7n7 提取码: c7n7 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by cenchaojun** [comment]
> 您好，新的链接如下，如再失效，请留言联系我哈~
> 
> 链接: https://pan.baidu.com/s/1ivAKHceZrh5uHRiKLiHcTw?pwd=c7n7 提取码: c7n7 复制这段内容后打开百度网盘手机App，操作更方便哦
非常感谢❤️

**Comment by winterswee** [comment]
可以再次提供新的链接吗？或者google云的，谢谢 @360-SSOD

**Comment by 360-SSOD** [comment]
@winterswee 您好!新地址如下：链接: https://pan.baidu.com/s/10uwb9q9MhNNCH_PSMqr5qA?pwd=rdss 提取码: rdss 经过测试百度网盘链接打开超过一定次数就会被屏蔽，如失效您可以邮件或者issues联系我，感谢您关注我们的工作！
