### ISSUE TITLE
百度云链接失效了

### ISSUE THREAD

**Issue by Orange-boy-2020** [360-SSOD/download#4]
你好，可以再次提供新的链接吗？感谢！

**Comment by 360-SSOD** [comment]
您好！实在抱歉，通知邮件被系统错分到垃圾邮箱中，刚看到。
网盘地址如下：链接: https://pan.baidu.com/s/10uwb9q9MhNNCH_PSMqr5qA?pwd=rdss 提取码: rdss 
感谢您关注我们的工作！
