### ISSUE TITLE
360SSOD测试集图片序号与提供的测试主观结果不匹配问题

### ISSUE THREAD

**Issue by YangTuo66** [360-SSOD/download#7]
您的工作中提供了360SSOD数据集上测试的主观结果图和原始数据集，但是主观结果图的序号与原始数据集中“dataset”表格的数据对应不上，请问这个问题如何解决。例如：主观结果图中的序号为0004、0007、0011、0013、0015、0021、0025......，但是“dataset”表格中依次是0007、0013、0015、0025、0040、0041、0045......。这在我们后续的工作中会导致客观指标的测试出错，以及主观结果比较用例图不匹配问题，还请帮忙解答一下，十分感谢。

**Comment by 360-SSOD** [comment]
您好！感谢您对我们工作的关注，您的表述我没太看懂，方便的话能截图下发我邮箱吗？


***@***.***&nbsp;，期待您的来信！
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, May 28, 2024 04:18 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[360-SSOD/download] 360SSOD测试集图片序号与提供的测试主观结果不匹配问题 (Issue #7)

&nbsp;



 
您的工作中提供了360SSOD数据集上测试的主观结果图和原始数据集，但是主观结果图的序号与原始数据集中“dataset”表格的数据对应不上，请问这个问题如何解决。例如：主观结果图中的序号为0004、0007、0011、0013、0015、0021、0025......，但是“dataset”表格中依次是0007、0013、0015、0025、0040、0041、0045......。这在我们后续的工作中会导致客观指标的测试出错，以及主观结果比较用例图不匹配问题，还请帮忙解答一下，十分感谢。

**Comment by YangTuo66** [comment]
下图第一张图片是您提供的result结果中图片序号和数据集中“dataset”表格中序号的对比，存在不匹配问题。第二张图中的右边为我根据表格从总数据集中划分出来的测试集，对比左右两张图中的图片存在不匹配的问题。那么在计算评价指标和对比主观结果就会存在误差。















Zelong&nbsp;Du
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "360-SSOD/download"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月28日(星期二) 晚上7:27
***@***.***&gt;;
抄送:&nbsp;"zl ***@***.******@***.***&gt;;
主题:&nbsp;Re: [360-SSOD/download] 360SSOD测试集图片序号与提供的测试主观结果不匹配问题 (Issue #7)





 您好！感谢您对我们工作的关注，您的表述我没太看懂，方便的话能截图下发我邮箱吗？ 
 
 
 ***@***.***&amp;nbsp;，期待您的来信！ 
 &amp;nbsp; 
 &amp;nbsp; 
 ------------------&amp;nbsp;Original&amp;nbsp;------------------ 
 From: ***@***.***&amp;gt;; 
 Date: &amp;nbsp;Tue, May 28, 2024 04:18 PM 
 To: ***@***.***&amp;gt;;  
 Cc: ***@***.***&amp;gt;;  
 Subject: &amp;nbsp;[360-SSOD/download] 360SSOD测试集图片序号与提供的测试主观结果不匹配问题 (Issue #7) 
 
 &amp;nbsp; 
 
 
 
   
 您的工作中提供了360SSOD数据集上测试的主观结果图和原始数据集，但是主观结果图的序号与原始数据集中“dataset”表格的数据对应不上，请问这个问题如何解决。例如：主观结果图中的序号为0004、0007、0011、0013、0015、0021、0025......，但是“dataset”表格中依次是0007、0013、0015、0025、0040、0041、0045......。这在我们后续的工作中会导致客观指标的测试出错，以及主观结果比较用例图不匹配问题，还请帮忙解答一下，十分感谢。

**Comment by YangTuo66** [comment]
不好意思，刚才那条回复是不是看不清楚图片，您能提供一个邮箱吗？

**Comment by 360-SSOD** [comment]
m中文g中文x&nbsp; (@) jbeta(中文)net 刚才回复了，但是被屏蔽了。您去掉所有的中文这次您看下是否可以？
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, May 28, 2024 07:58 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [360-SSOD/download] 360SSOD测试集图片序号与提供的测试主观结果不匹配问题 (Issue #7)

&nbsp;



 
不好意思，刚才那条回复是不是看不清楚图片，您能提供一个邮箱吗？

**Comment by YangTuo66** [comment]
![附件2](https://github.com/360-SSOD/download/assets/119663767/e479b02b-09a3-4380-8674-5d528f5bb6ff)
![附件1](https://github.com/360-SSOD/download/assets/119663767/cd3a9610-97dd-450f-be66-9a051454a9fa)

**Comment by YangTuo66** [comment]
下图第一张图片是您提供的result结果中图片序号和数据集中“dataset”表格中序号的对比，存在不匹配问题。第二张图中的右边为我根据表格从总数据集中划分出来的测试集，对比左右两张图中的图片存在不匹配的问题。那么在计算评价指标和对比主观结果就会存在误差。
![附件2](https://github.com/360-SSOD/download/assets/119663767/86990b59-d029-4a81-b008-6e0624f8074b)
![附件1](https://github.com/360-SSOD/download/assets/119663767/107129cb-5711-4374-8023-ba8fd8d4a929)

**Comment by YangTuo66** [comment]
下图第一张图片是您提供的result结果中图片序号和数据集中“dataset”表格中序号的对比，存在不匹配问题。第二张图中的右边为我根据表格从总数据集中划分出来的测试集，对比左右两张图中的图片存在不匹配的问题。那么在计算评价指标和对比主观结果就会存在误差。
![附件1](https://github.com/360-SSOD/download/assets/119663767/02020846-058e-4e72-8ca3-33f856987320)
![附件2](https://github.com/360-SSOD/download/assets/119663767/bb77ef46-6c13-4536-aa2e-1186a42ae692)

**Comment by YangTuo66** [comment]
邮箱格式一直有问题，所以我就直接上传图片了，请见谅。

**Comment by 360-SSOD** [comment]
您好，图片看到了，原因找到了，您下载的是Result-all这个压缩包吗？这个包是另一篇工作中随机分配测试集后的结果，原始结果被百度云屏蔽了，应该是标题为Result的压缩包，我尝试上传几次都被屏蔽了，您到&nbsp;https://github.com/360-SSOD/download 底部有个我的邮箱，麻烦您给我发个邮件，我将Result的压缩包发您哈，实在抱歉！
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, May 28, 2024 08:15 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [360-SSOD/download] 360SSOD测试集图片序号与提供的测试主观结果不匹配问题 (Issue #7)

&nbsp;



 
邮箱格式一直有问题，所以我就直接上传图片了，请见谅。
